### ISSUE TITLE
Native differ crashes on certain input

### ISSUE THREAD

**Issue by michael-o** [maintaina-com/Text_Diff#12]
While working on further testing of WebSVN I get the following exception:
```
Fatal error: Uncaught AssertionError: assert($y <= $this->seq[$k]) in /usr/local/www/websvn/vendor/horde/text_diff/lib/Horde/Text/Diff/Engine/Native.php:244
Stack trace:
#0 /usr/local/www/websvn/vendor/horde/text_diff/lib/Horde/Text/Diff/Engine/Native.php(244): assert(false, 'assert($y <= $t...')
#1 /usr/local/www/websvn/vendor/horde/text_diff/lib/Horde/Text/Diff/Engine/Native.php(328): Horde_Text_Diff_Engine_Native->_diag(0, 8, 0, 8, 8)
#2 /usr/local/www/websvn/vendor/horde/text_diff/lib/Horde/Text/Diff/Engine/Native.php(131): Horde_Text_Diff_Engine_Native->_compareseq(0, 8, 0, 8)
#3 /usr/local/www/websvn/vendor/horde/text_diff/lib/Horde/Text/Diff.php(49): Horde_Text_Diff_Engine_Native->diff(Array, Array)
#4 /usr/local/www/websvn/text-diff-native-fail.php(91): Horde_Text_Diff->__construct(Object(Horde_Text_Diff_Engine_Native), Array)
#5 {main}
  thrown in /usr/local/www/websvn/vendor/horde/text_diff/lib/Horde/Text/Diff/Engine/Native.php on line 244
```

I am on:
```
# php --version
PHP 8.2.0beta2 (cli) (built: Sep  9 2022 17:07:28) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.0-dev, Copyright (c) Zend Technologies
```
Here is a test case:
[text-diff-native-fail.php.txt](https://github.com/maintaina-com/Text_Diff/files/9602306/text-diff-native-fail.php.txt)

FWIW: Xdiff does not fail, only Native fails.

**Comment by ralflang** [comment]
Interesting. I will try to compose a unit test from this one.

**Comment by michael-o** [comment]
FWIW: This is a colorized diff generated by GeSHi. When diffing the original Java files no exception is thrown. If required I can provide both revisions of the Java file.

**Comment by michael-o** [comment]
Did further testing. Same on PHP 8.0.x, 8.1.x. On 7.4.x I get the following:
![grafik](https://user-images.githubusercontent.com/573017/191276496-32281e85-3578-459b-93fc-73de0da4509e.png)

**Comment by ralflang** [comment]
This is a mean one.
By default, this runs on PHP 7.4 but not on 8.x - but let's not be fooled. This is due to assertions failing by default in PHP 8 while they needed to be explicitly turned on in PHP 7.4.

Now I went back until PHP 5.2 - This is not an upgrade issue.
Even 5.2 dislikes this assumption. 

However, the code seems to produce a reasonable diff if the assertion is ignored.
I am tempted to disable the assertion for now and postpone looking for a deeper algorithmic issue.

What do you think?

**Comment by michael-o** [comment]
> This is a mean one. By default, this runs on PHP 7.4 but not on 8.x - but let's not be fooled. This is due to assertions failing by default in PHP 8 while they needed to be explicitly turned on in PHP 7.4.
> 
> Now I went back until PHP 5.2 - This is not an upgrade issue. Even 5.2 dislikes this assumption.
> 
> However, the code seems to produce a reasonable diff if the assertion is ignored. I am tempted to disable the assertion for now and postpone looking for a deeper algorithmic issue.
> 
> What do you think?

I agree with you.

**Comment by michael-o** [comment]
Created PR to resort this for now. @ralflang Can you please have a look?
